Various text improvements following from user testing
hypergraph-xyz/desktop pull request #233
Opened 2020-08-21 14:53 UTC by jameslibscie

Changes:
- Consistent use of "step" instead of "part" in welcome modals
- "Finding a journal" -> "becoming accepted by a journal"
- "Hypergraph Vault is our cloud service"
- "Nudges" on all pages with icon hints on how to get started
- Removed "No main" text on edit content form to make it visually clearer that nothing is selected

@psobrakseaton there are some small design implications because I'm including the Find icon on other pages for the first time. It's probably enough to just check these screenshots:

![image](https://user-images.githubusercontent.com/59870484/90903701-99b89380-e3ce-11ea-9b92-2262abd90060.png)
![image](https://user-images.githubusercontent.com/59870484/90903708-9d4c1a80-e3ce-11ea-8e86-421ecc8069ed.png)
![image](https://user-images.githubusercontent.com/59870484/90903717-a0470b00-e3ce-11ea-8500-50bd36aaba04.png)

Curious for opinions! If there are any major doubts, I will just scrap these changes as this is technically non-planned work that is only worth the effort if we can merge fast imo.

Closes #202

2020-08-24 06:53 UTC, juliangruber requested changes

2020-08-24 06:53 UTC, juliangruber commented on app/components/content/edit-form.js
> +          <option value='' />
It looks to be common UX practice to have a word for the blank option: https://ux.stackexchange.com/questions/36633/best-wording-of-blank-option-for-an-optional-select. Why did you change this? Maybe we could find a better replacement.

2020-08-24 06:53 UTC, juliangruber commented on app/components/feed/feed.js
> +                  : <>Add content with <StyledAddContent /> or <StyledSearch /> Find someone to follow 🙌</>}
To me the mixture of multiple icons and emojis is visual overload. What about either removing the emojis or scaling down the icons so they don't stick out of the text flow?

2020-08-24 06:53 UTC, juliangruber commented on app/components/feed/feed.js
> +`
This can by DRYed up. Let's revisit it once we decided on a strategy from a visual perspective.

2020-08-24 06:53 UTC, juliangruber commented on app/components/welcome/welcome.js
> +        With Hypergraph, you can publish each step of your research as-you-go.
:+1:

2020-08-24 06:53 UTC, juliangruber commented on app/components/welcome/welcome.js
> +        Each step of your research is its own publication, whether it's a
:+1:

2020-08-24 06:53 UTC, juliangruber commented on app/components/welcome/welcome.js
> +          Hypergraph Vault is our cloud service that makes your work available
```suggestion
          Hypergraph Vault is our service that makes your work available
```

Cloud has a negative connotation, especially in the P2P space. I'm also not sure this level of technicality is helpful here. Any reasons for specifically mentioning it?

Also, we aren't sure it even is going to be a cloud service, at all. It can run just fine on Chris' laptop, and maybe it will end up in some data centers and never the cloud.

2020-08-24 09:38 UTC, jameslibscie commented on app/components/content/edit-form.js
> +          <option value='' />
There were two reasons:
1. Consistency -> follows from dropdown is also empty when there is no option selected
2. Users sometimes seem to skip over this dropdown, I was thinking perhaps because there is already something filled in.

Given your link, I'd prefer to then change both to "None" rather than leave them empty. This is common and apparently also preferred UX-wise.

2020-08-24 09:49 UTC, jameslibscie commented on app/components/welcome/welcome.js
> +          Hypergraph Vault is our cloud service that makes your work available
I didn't know about the negative connotation. How about "hosting" or "storage" then? I'm looking for simple ways to illustrate the difference between using the vault and not using the vault without literally explaining everything in detail.

For example, during one of last week's tests, it was thought or considered for a while that the vault would also be p2p-based and might require users to offer bandwidth and storage. The word "cloud" came up as something that is nowadays understood as something like "we'll take of your files for you" and implies safety.

2020-08-24 10:00 UTC, jameslibscie commented on app/components/feed/feed.js
> +                  : <>Add content with <StyledAddContent /> or <StyledSearch /> Find someone to follow 🙌</>}
I kinda missed the emoji, so I've tried smaller icons. What do you think?

2020-08-26 11:40 UTC, chartgerink commented on app/components/feed/feed.js
> +`
Could you explain the acronym? Tried googling but to no avail.

2020-08-26 11:42 UTC, jameslibscie commented on app/components/feed/feed.js
> +`
"don't repeat yourself"

2020-08-26 11:44 UTC, chartgerink approved these changes
Minor comments that you can do with as you see fit :) Nice work!

2020-08-26 11:44 UTC, chartgerink commented on app/components/profile/following.js
> +                : <>You’re not following anybody yet. 😅 Use <StyledSearch /> Find to look up a profile</>
```suggestion
                : <>You’re not following anybody yet. 😅 Use "<StyledSearch /> Find" to look up a profile</>
```

I was confused by this as I read "Find to look up a profile" 😅

2020-08-26 11:44 UTC, chartgerink commented on app/components/welcome/welcome.js
> +        going through the laborious process of becoming accepted by a journal.
```suggestion
        going through the laborious process of getting accepted by a journal.
```

Becoming accepted sounds very existential, as researcher I'd use this phrasing (publication gets accepted).

2020-08-26 11:44 UTC, chartgerink commented on app/components/welcome/welcome.js
> +          We do not want to be gatekeepers. We chose peer-to-peer technology so you can
YAAAS!

2020-08-28 07:07 UTC, juliangruber requested changes

2020-08-28 07:07 UTC, juliangruber commented on app/components/drafts/drafts.js
> +  margin-right: -6px;
you could also remove the white space from the text surrounding it instead:

![image](https://user-images.githubusercontent.com/10247/91531378-fd7e1780-e90c-11ea-82aa-cd04adcf36d3.png)

2020-08-28 07:07 UTC, juliangruber commented on app/components/feed/feed.js
> +`
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself. It's more of a programming joke / slang I'd say to use it this way

2020-08-28 07:07 UTC, juliangruber commented on app/components/feed/feed.js
> +                  : <>Add content with <StyledAddContent /> or <StyledSearch /> Find someone to follow 🙌</>}
![image](https://user-images.githubusercontent.com/10247/91531604-55b51980-e90d-11ea-818d-9bd2e8148259.png)

This doesn't read well to me, I'd like to hear @psobrakseaton's perspective.

1) The add content icon is to the right while the find icon is to the left
2) What about removing the "with" from "add content with"?

2020-08-28 07:07 UTC, juliangruber commented on app/components/profile/following.js
> +                : <>You’re not following anybody yet. 😅 Use <StyledSearch /> Find to look up a profile</>
```suggestion
                : <>You’re not following anybody yet 😅 Use <StyledSearch /> Find to look up a profile</>
```

Didn't we say in the welcome modals that emojis replace punctuation?

2020-08-28 07:07 UTC, juliangruber commented on app/components/profile/following.js
> +                : <>You’re not following anybody yet. 😅 Use <StyledSearch /> Find to look up a profile</>
I noticed this too. Not sure "Find 🔎" is enough. @psobrakseaton what do you think?

2020-08-28 07:07 UTC, juliangruber commented on app/components/profile/profile.js
> +                : <>No content yet... 🤔 Use <StyledAddContent /> to add something!</>
![image](https://user-images.githubusercontent.com/10247/91531886-cb20ea00-e90d-11ea-8e86-71e18516fef3.png)

To my eyes there's just too many icons in here

2020-08-28 09:25 UTC, psobrakseaton commented on app/components/profile/profile.js
> +                : <>No content yet... 🤔 Use <StyledAddContent /> to add something!</>
I also think that we need another word, like "Use 🔎 Find to input a URL". 

I think the emojis are cute, but we should try to limit them if we are already using icons. It is throwing off my perception of the punctuation and making it hard to parse the sentence.

2020-08-28 09:26 UTC, psobrakseaton commented on app/components/profile/profile.js
> +                : <>No content yet... 🤔 Use <StyledAddContent /> to add something!</>
I think we either need to separate something by lines, or go for a simpler solution only using the add-content button.

2020-08-28 09:27 UTC, psobrakseaton commented
@jameslibscie can you post a list of all the changed messages in a single comment?

2020-08-28 10:12 UTC, psobrakseaton commented
We're solving this during a phone call...

2020-08-28 12:49 UTC, juliangruber approved these changes

2020-08-28 14:04 UTC, merged