Add archive in Vault
hypergraph-xyz/desktop pull request #253
Opened 2020-09-01 11:57 UTC by juliangruber

2020-09-01 13:03 UTC, psobrakseaton approved these changes

2020-09-01 13:43 UTC, jameslibscie requested changes
The vault seems to get enabled (judging by the menu bar text) regardless of whether I click "Enable the Vault" or "Skip for now..."

2020-09-01 14:01 UTC, jameslibscie commented
Currently on an unstable connection and got this error:
![image](https://user-images.githubusercontent.com/59870484/91860746-567ee000-ec6c-11ea-8697-654dfc925e0c.png)

I'm also wondering, how do we handle it if someone adds content to their profile while their internet connection is down? It still needs to find its way to the vault somehow.

2020-09-01 14:44 UTC, juliangruber commented
We can keep retrying, yes, also across restarts.

Do you think this is something that would need to be exposed in the UI

2020-09-01 14:44 UTC, juliangruber commented
Good point to check for offline breakage..

2020-09-02 06:37 UTC, juliangruber commented
I fixed the vault always being enabled and also added a 1s loop that will try to upload any previously failed modules, as well es not throwing an error when uploading failed.

2020-09-02 08:01 UTC, chartgerink requested changes
This is looking awesome 😄 I really like how frictionless the Vault integrates. 

My only main question is: Would the Vault need to be disabled upon reset of the database? The Hypergraph Vault stays enabled at the moment (no problem) and doesn't disable when I use the "Skip for now" option. I would expect the Vault to be disabled when I don't click "Enable Vault". What do you think?

Also double checked the offline issue, and all works well on my end 😊 

EDIT: My suggestions are minor, the only reason I didn't approve is the question above.

2020-09-02 08:44 UTC, jameslibscie commented on app/components/welcome/welcome.js
> +              Enable the Vault
Dropbox now too! I think as long as we introduce it as Hypergraph Vault it's OK and clear that we're referring to our own vault, but it can't hurt to reiterate at key moments.

2020-09-02 08:46 UTC, psobrakseaton commented on app/components/welcome/welcome.js
> +              Enable the Vault
+1 to this.

2020-09-02 09:00 UTC, jameslibscie reviewed
Works great!
I'm wondering though about Chris's comment about resetting the DB and then also the re-open welcome modals issue as they both allow the user to make a choice again. Should "Skip for now..." then disable the vault? I'm leaning towards yes, and then perhaps replacing this button with a "Disable" button later on if the setting is already present (or just implementing that now?). Kinda unlikely scenarios early on, but I think it's quite a key part of the software and something that we should be clear on. Would be a shame to lose some users' trust over this.

2020-09-03 06:41 UTC, juliangruber commented on app/lib/vault.js
> +  store.set('queue', [...queue, url])
> As I read the code (might well be wrong) this is doing an unauthenticated POST request to the server; is this correct?

This is correct.

> Is it possible for people to feed the Hypergraph Vault random Hyper(graph) keys outside of this environment, if they were to inspect the code or their packets?

Yes, they could figure this out either by reading Desktop's, CLI's or the source code of the Hypergraph Vault itself.

There's no way to add a "secret" to Hypergraph Desktop that can't be discovered, the only way to secure this is by requiring the user to log in with the Vault, for which we don't have the UI yet.

I think this is good for now, at our size an attack is a good indicator, if anything.

2020-09-03 06:42 UTC, juliangruber commented
> Would the Vault need to be disabled upon reset of the database?

I don't think so, since the database is a p2pcommons feature, while the vault is not directly related to it. In this sense, clearing the database means resetting the data, but _not_ the app settings.

I fixed the "Skip for now..." button not disabling the vault. And when you reset the database, you'll be prompted for the vault setting anyway.

2020-09-03 09:09 UTC, juliangruber commented
via @chartgerink:

![image](https://user-images.githubusercontent.com/10247/92095358-d8d6e380-edd5-11ea-8333-f35cc6e20e28.png)

2020-09-07 12:31 UTC, juliangruber commented
> via @chartgerink:

This has been fixed in main :)

2020-09-08 08:54 UTC, chartgerink approved these changes
Yay all works 🎉 

My only minor comment that is not blocking merge: When I enable vault in the welcome modals, the menu bar doesn't switch until I restart the application.

2020-09-08 09:33 UTC, juliangruber commented
> When I enable vault in the welcome modals, the menu bar doesn't switch until I restart the application.

Oh dang this works on Windows, I'll, have to retest

2020-09-08 11:31 UTC, chartgerink approved these changes
![](https://media.giphy.com/media/dXjaXGjVdExGuisFFg/giphy.gif)

2020-09-08 11:32 UTC, merged