Add Terms Of Use. Closes #225
hypergraph-xyz/desktop pull request #262
Opened 2020-09-10 09:11 UTC by juliangruber

Whenever the welcome screens are shown _and_ there is no profile (ie after database reset or first start), the Terms Of Use display.

I have removed the analytics checkbox for now since I'm not aware of a work item to add analytics.

Closes #225.

![image](https://user-images.githubusercontent.com/10247/92708104-27482d00-f356-11ea-9764-edad8d4b7ae0.png)

2020-09-10 12:17 UTC, psobrakseaton commented
> Whenever the welcome screens are shown _and_ there is no profile (ie after database reset or first start), the Terms Of Use display.
> 
> I have removed the analytics checkbox for now since I'm not aware of a work item to add analytics.
> 
> Closes #225.
> 
> ![image](https://user-images.githubusercontent.com/10247/92708104-27482d00-f356-11ea-9764-edad8d4b7ae0.png)

Weird question, but do you think that even if we don't have active analytics, having the consent for them still makes sense? @chartgerink, do you want to weigh in here?

2020-09-10 12:51 UTC, chartgerink requested changes
The links didn't open in the browser. I think the suggestions fix that?

Usage statistics/analytics was part of another work item that I own, which was why I mentioned it in the issue for the Terms. 

Could you please add the checkbox? The copy is:

> Allow statistics to be sent to Liberate Science GmbH

Default would be checked, and if it is checked upon "agree" [this linked code in Notion](https://www.notion.so/libscie/Implement-website-desktop-analytics-a1736fde6d174ddb93068c8a54d80951#a2a1b1ce9a1d4ade82e30cbe35b68d0f) should be injected into the head.

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +import React from 'react'
```suggestion
import React from 'react'
import Anchor from '../anchor'
```

For external links to open in browser, not the app.

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +        </a>
```suggestion
        <Anchor href='https://creativecommons.org/publicdomain/zero/1.0/legalcode'>
          CC0 Public Domain Dedication
        </Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +        </a>{' '}
```suggestion
        <Anchor href='https://creativecommons.org/publicdomain/zero/1.0/legalcode'>
          CC0 Public Domain Dedication
        </Anchor>{' '}
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +        </a>
```suggestion
        <Anchor href='https://en.wikipedia.org/wiki/Burden_of_proof_(law)#Preponderance_of_the_evidence'>
          preponderance of evidence
        </Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          <a href='https://aws.amazon.com/privacy/'>Amazon Web Services</a>
```suggestion
          <Anchor href='https://aws.amazon.com/privacy/'>Amazon Web Services</Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          <a href='https://chatra.com/privacy-policy/'>Chatra</a>
```suggestion
          <Anchor href='https://chatra.com/privacy-policy/'>Chatra</Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          <a href='https://cloud68.co/legal/privacy-policy'>Cloud68</a>
```suggestion
          <Anchor href='https://cloud68.co/legal/privacy-policy'>Cloud68</Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          </a>
```suggestion
          <Anchor href='https://www.digitalocean.com/legal/privacy-policy/'>
            DigitalOcean
          </Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          <a href='https://policies.google.com/privacy'>Google App Suite</a>
```suggestion
          <Anchor href='https://policies.google.com/privacy'>Google App Suite</Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          </a>
```suggestion
          <a href='https://www.notion.so/Privacy-Policy-3468d120cf614d4c9014c09f6adc9091'>
            Notion
          </a>
```
```suggestion
          <Anchor href='https://www.notion.so/Privacy-Policy-3468d120cf614d4c9014c09f6adc9091'>
            Notion
          </Anchor>
```

2020-09-10 12:51 UTC, chartgerink commented on app/components/welcome/terms-of-use.js
> +          <a href='https://stripe.com/en-de/privacy'>Stripe</a>
```suggestion
          <Anchor href='https://stripe.com/en-de/privacy'>Stripe</Anchor>
```

2020-09-12 10:57 UTC, juliangruber commented
> The links didn't open in the browser. I think the suggestions fix that?

I forgot about those, good catch!

I implemented it differently however, since your solution would make it hard to update the Terms if they ever change, since the Anchors need to be manually replaced every time.

2020-09-12 10:58 UTC, juliangruber commented
> Could you please add the checkbox? The copy is:
> 
> > Allow statistics to be sent to Liberate Science GmbH
> 
> Default would be checked, and if it is checked upon "agree" [this linked code in Notion](https://www.notion.so/libscie/Implement-website-desktop-analytics-a1736fde6d174ddb93068c8a54d80951#a2a1b1ce9a1d4ade82e30cbe35b68d0f) should be injected into the head.

This is a separate work item, I'm going to open an issue for this. If we add the checkbox now but don't add the code behind it yet, there's a broken feature in the app

2020-09-14 08:55 UTC, chartgerink commented
> > The links didn't open in the browser. I think the suggestions fix that?
> 
> I forgot about those, good catch!
> 
> I implemented it differently however, since your solution would make it hard to update the Terms if they ever change, since the Anchors need to be manually replaced every time.

Yes, that's great! Thanks. 

I tried reviewing again; I don't see any newer commits since last time?

2020-09-14 08:57 UTC, juliangruber commented
> I tried reviewing again; I don't see any newer commits since last time?

Yeah, when someone requests a review that can also mean they ask you to reconsider your last review, after new information has been shared. Before I re-requested it, your state was still "requests changes".

2020-09-14 09:11 UTC, chartgerink commented
Ah okay :) I agree with the plan of action. 

The links still open in the electron environment, so I guess I'll not approve just yet?

2020-09-14 09:29 UTC, juliangruber commented
Dang I'm sorry, forgot to push

2020-09-14 11:50 UTC, chartgerink approved these changes

2020-09-14 11:52 UTC, psobrakseaton approved these changes

2020-09-14 12:59 UTC, merged