Add key backup modal
hypergraph-xyz/desktop pull request #350
Opened 2021-02-05 09:26 UTC by chartgerink

This PR adds a modal that forces users to back up their key. This is based on the experience that users did not follow on the welcome tour instructions and ended up not creating a backup of their private key. The implemented design is as follows (illustration provided by @psobrakseaton):

<img width="1552" alt="Screenshot 2021-02-05 at 10 21 23" src="https://user-images.githubusercontent.com/2946344/107014714-48456a80-679c-11eb-9a9c-c0873566ca66.png">

Note: This modal does not yet appear for existing users of Hypergraph. There is some commented out code in the pull request that aimed to implement this, but alas, I ran into a wall with how the modals were set up. I ended up paginating to the extent that it hit `if (!dialogs[page]) return null` which logically led to a black screen upon close. Any help appreciated to make existing users also back up their keys :)

2021-02-05 09:40 UTC, juliangruber commented
> There is some commented out code in the pull request that aimed to implement this, but alas, I ran into a wall with how the modals were set up. I

Yeah, showing just one slide wasn't considered with the initial design.

2021-02-05 09:41 UTC, juliangruber commented
> Any help appreciated to make existing users also back up their keys :)

You could show a `Notification` and on click do the same thing as the `Copy your key` button?

2021-02-05 09:44 UTC, juliangruber commented on app/index.js
> +  // const [keyCopied, setKeyCopied] = useState()
is this still a WIP / should it be a draft PR?

2021-02-05 09:44 UTC, juliangruber commented on index.js
> +                store.set('keyCopied', true)
`keyBackedUp` would be more semantic

2021-02-07 19:50 UTC, chartgerink commented on index.js
> +                store.set('keyCopied', true)
Thanks! I changed it. I am still getting the hang of semantic naming and your guidance helps ☺️

2021-02-07 19:51 UTC, chartgerink commented on app/index.js
> +  // const [keyCopied, setKeyCopied] = useState()
I was sloppy. 😅  Removed it.

2021-02-08 09:32 UTC, juliangruber requested changes

2021-02-08 09:32 UTC, juliangruber commented on app/components/welcome/welcome.js
> +const AdmZip = require('adm-zip')
this file use `import` syntax

2021-02-08 09:32 UTC, juliangruber commented on app/components/welcome/welcome.js
> +  const [page, setPage] = useState(start || (profileUrl ? 1 : 0))
the `start` option seems not to be used

2021-02-08 09:32 UTC, juliangruber commented on app/index.js
> +  ) : (
nice!

2021-02-08 09:32 UTC, juliangruber commented on index.js
> +        'To ensure you keep access to your account, back up your key now. Click here.'
This doesn't read friendly to me. What about something like

> To ensure you keep access to your account, back up your key by clicking here.

2021-02-11 10:04 UTC, merged