Add markdown main rendering
hypergraph-xyz/desktop pull request #356
Opened 2021-02-09 14:31 UTC by chartgerink

This PR adds rendering of main files of `*.md`. Includes:
* Equation rendering
* Table rendering
* Image rendering
* Support for module relative paths (`./imgs/test-image.png` is served through `express` that works on the `p2pcommons` folder).

<img width="2160" alt="Screenshot 2021-02-09 at 15 18 37" src="https://user-images.githubusercontent.com/2946344/107377817-a8fddb80-6aeb-11eb-9a86-61f91792683a.png">
<img width="2160" alt="Screenshot 2021-02-09 at 15 18 49" src="https://user-images.githubusercontent.com/2946344/107377861-b61aca80-6aeb-11eb-9559-b9f374183ff3.png">

@psobrakseaton I invited your review to see whether the visual changes I made are to your approval until we address the redesign of the entire content display.

2021-02-09 14:56 UTC, juliangruber requested changes

2021-02-09 14:56 UTC, juliangruber commented on app/components/content/content.js
> +        const md = await (
no need for the double await here, since `.toString()` is synchronous

2021-02-09 14:56 UTC, juliangruber commented on app/components/content/content.js
> +      if (mdExtMain.test(content.rawJSON.main)) {
Simpler:

```suggestion
      if (content.rawJSON.main.endsWith('.md')) {
```

2021-02-09 14:56 UTC, juliangruber commented on app/components/content/content.js
> +  const protoTest = new RegExp(/https?/)
This can also be `string.startsWith('http')`

2021-02-09 14:56 UTC, juliangruber commented on index.js
> +const localStorage = express()
`localStorage` is a term already known from browsers, where it's a built in api. Try `localStorage` in the devtools.

2021-02-09 14:56 UTC, juliangruber commented on index.js
> +localStorage.listen(5152, () => {})
No need to add a callback

2021-02-11 12:06 UTC, chartgerink commented on app/components/content/content.js
> +        const md = await (
It returns a Promise if I remove the await, and does not end up rendering the content. I left it in there for now.

2021-02-17 09:18 UTC, psobrakseaton approved these changes
The visual changes look really nice! Approved!

2021-02-17 09:32 UTC, merged