Add option to show terms upon update
hypergraph-xyz/desktop pull request #357
Opened 2021-02-09 19:24 UTC by chartgerink

This PR adds the option to hardcode reappearance of the terms when updating the application.

Specifically, whenever the terms are updated before release, the `welcome` and `terms` storevalue should be flipped to true. In the PR they are set to `false` given that the terms have not yet been updated in `main`. This will then show the terms to users after the app is updated (plus the final welcome screen). Specifically, it is this tidbit that needs to be changed in `./index.js`: 
```
if (!(app.getVersion() === store.get('lastVersion'))) {
  store.set('welcome', false)
  store.set('terms', false)
}
```

I implemented it by skipping all the pages between the terms and the final welcome screen. This is due to the welcome screens at the moment not being designed for single display (per [this comment](https://github.com/hypergraph-xyz/desktop/pull/350#issuecomment-773917757)). This was my inelegant approach to be able to add it at the moment, but we might want to reconsider the way the welcome screens are setup in the future if this proves too clunky.

![](https://media.giphy.com/media/oS8pRFxbD0d44/giphy.gif)

2021-02-10 08:40 UTC, juliangruber requested changes

2021-02-10 08:40 UTC, juliangruber commented on app/components/welcome/welcome.js
> +    return (
unnecessary syntax change

2021-02-10 08:40 UTC, juliangruber commented on app/components/welcome/welcome.js
> +              'lastVersion',
not clear which version this is, what about `'currentAppVersion'` or `'lastInstalledAppVersion'`?

2021-02-10 08:40 UTC, juliangruber commented on app/components/welcome/welcome.js
> +            await ipcRenderer.invoke('setStoreValue', 'terms', false)
Why do we set `terms` to `false` here, right after the user saw them? I didn't get that part in the PR description

2021-02-10 08:40 UTC, juliangruber commented on app/components/welcome/welcome.js
> +    if (skip) next()
Instead of each slide manually skipping, the slide manager can simply modify the current page index

2021-02-14 15:18 UTC, chartgerink commented on app/components/welcome/welcome.js
> +              'lastVersion',
Good point. `lastInstalledAppVersion` is the best depiction. I updated accordingly :)

2021-02-14 15:21 UTC, chartgerink commented on app/components/welcome/welcome.js
> +            await ipcRenderer.invoke('setStoreValue', 'terms', false)
Hm, the intent is to update it to `false` after the person accepts the terms. `terms` is meant as `showTerms`, which might be the confusing part? I based it off the `welcome` store that functioned more as `showWelcome` too.

2021-02-14 15:44 UTC, chartgerink commented on app/components/welcome/welcome.js
> +    if (skip) next()
lol indeed. 👍

2021-02-14 19:11 UTC, juliangruber commented on app/components/welcome/welcome.js
> +            await ipcRenderer.invoke('setStoreValue', 'terms', false)
ah right. Yeah I think that's exactly it!

2021-02-15 12:36 UTC, chartgerink commented on app/components/welcome/welcome.js
> +            await ipcRenderer.invoke('setStoreValue', 'terms', false)
Updated the store names to be more verbose :)

2021-02-15 15:09 UTC, merged